booking/urls.py
from django.urls import path
from . import views
from booking.views import *

urlpatterns = [
    path(
        'addbooking/', views.add_booking,
        name='addbooking'
    ),
    path(
       'viewbooking/', views.view_booking,
       name='viewbooking'
    ),
    path(
        'editbooking/<str:pk>/', views.edit_booking,
        name='editbooking'
    ),
    path(
        'deletebooking/<str:pk>/', views.delete_booking,
        name='deletebooking'
    ),   
]

home/urls.py
from django.urls import path
from home.views import HomePage


urlpatterns = [
    path('', HomePage.as_view(), name='home'),
]

menu/urls.py
from django.urls import path
from . import views
from menu.views import MenuPage


urlpatterns = [
    path('', views.MenuPage, name='menu'),
]

smorrebrod/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('allauth.urls')),
    path('addbooking/', include('booking.urls')),
    path('menu/', include('menu.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'booking.views.error_404_view'

booking/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.contrib.auth.models import User


# Choices for Time Slots and capacity
capacity = ((2, "2"), (4, "4"), (6, "6"), (8, "8"), (10, "10"),
            (12, "12"), (20, "20"))
time_slots = ((1, "1:00pm - 2:50pm"), (2, "3:00pm - 4:50pm"),
              (3, "5:00pm - 6:50pm"), (4, "7:00pm - 8:50pm"),
              (5, "9:00pm - 10:50pm"))


# Table and Booking Model
class Table(models.Model):
    """ Creating Tables Model """
    table_id = models.IntegerField(unique=True)
    table_capacity = models.IntegerField(choices=capacity, default=2)

    class Meta:
        """ Order by table number """
        ordering = ['table_id']

    def __str__(self):
        return str(self.table_id)


class Booking(models.Model):
    """ Creating Booking Model """
    customer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='booking_guest',
        null=True,
        blank=True
    )
    name = models.CharField(max_length=50, null=True)
    phone_number = models.CharField(max_length=20)
    booking_time = models.IntegerField(choices=time_slots, default=1)
    party_size = models.IntegerField(default=2)
    booking_date = models.DateField()
    booking_table = models.ForeignKey(
        Table, on_delete=models.CASCADE,
        related_name="booked_table",
        null=True,
        blank=True 
    )

    def __str__(self):
        return f"{self.customer} - {self.booking_date} {self.booking_time}"

home/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


class Item(models.Model):
    """ Best Menu Items Model """
    name = models.CharField(max_length=50, unique=True)
    image = CloudinaryField(height_field=None)
  
    def __str__(self):
        return str(self.name)

booking/forms.py
from django import forms
from django.core.exceptions import ValidationError
from datetime import datetime
from .widget import DatePickerInput
from .models import Booking


class BookingTableForm(forms.ModelForm):
    """ Create form from Model """
    class Meta:
        model = Booking
        fields = [
            'name',
            'phone_number',
            'party_size',
            'booking_time',
            'booking_date',
        ]
        widgets = {
            'booking_date': DatePickerInput(),
        }
        labels = {
            'name': 'Name',
            'phone_number': 'Phone Number',
            'booking_time': 'Time',
            'booking_date': 'Date',
            'party_size': 'Party Size',
        }

    def clean_booking_date(self):
        booking_date = self.cleaned_data.get('booking_date')
        if booking_date < datetime.today().date():
            raise forms.ValidationError('Date cannot be in passed')
        return booking_date

    def clean_party_size(self):
        party_size = self.cleaned_data.get('party_size')
        if party_size <= 0:
            raise forms.ValidationError('Party size must not be less then 1')
        return party_size

booking/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Booking, Table
from .forms import BookingTableForm


def error_404_view(request, exception):
    return render(request, '404_error.html')


@login_required
def add_booking(request):
    """
    Creation of booking by customer and adding it to db
    """
    form = BookingTableForm()
    if request.method == 'POST':
        form = BookingTableForm(request.POST)
        if form.is_valid():
            booking = form.save()
            booking.customer = request.user
            booking.save()
            messages.success(request, 'Booking is successful.')
            return redirect('viewbooking')
    context = {
        'form': form
        }
    return render(request, 'booking.html', context)


@login_required
def view_booking(request):
    """
    Function enables user to view a booking after
    it has been made and added to the database.
    """
    bookings = Booking.objects.filter(customer__in=[request.user])
    context = {
        'bookings': bookings
        }
    return render(request, 'view_booking.html', context)


@login_required
def edit_booking(request, pk):
    booking = Booking.objects.get(id=pk)
    form = BookingTableForm(instance=booking)
    if request.method == 'POST':
        form = BookingTableForm(request.POST, instance)
        if form.is_valid():
            booking = form.save()
            booking.customer = request.user
            booking.save()
            messages.success(request, 'Booking is updated successfuly.')
            return redirect('viewbooking')
    context = {'form': form}
    return render(request, 'booking.html', context)


@login_required
def delete_booking(request, pk):
    booking = Booking.objects.get(id=pk)
    if request.method == 'POST':
        booking.delete()
        messages.success(request, 'Booking is deleted successfuly.')
        return redirect('viewbooking')
    context = {'booking': booking}
    return render(request, 'delete_booking.html', context)

home/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    """
    View to render homepage
    """
    template_name = 'index.html'

menu/views.py
from django.urls import path
from django.shortcuts import render
from menu.models import Item


def MenuPage(request):
    menu = Item.objects.all()
    context = {
        'menu': menu
    }
    return render(request, 'menu.html', context=context)

booking/templates/booking.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}

<div class="jumbotron jumbotron-fluid" style=" background-image: url('{% static 'images/5.jpeg' %}')">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 offset-md-2">
                <form method="POST" action="{% url 'addbooking' %}" name="form">

                    {{ form|crispy }}
                    {{ form.media }}
                    {% csrf_token %}


                    <div class="intro-button mx-auto"><button class="btn btn-danger col-md-12" type="submit">Submit
                            Booking</button>
                    </div>

                </form>
            </div>
        </div>
    </div>

        </div>
    </div>
</div>
</div>


{% endblock content %}

booking/templates/delete_booking.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron jumbotron-fluid" style="background-image: url('{% static 'images/5.jpeg' %}')">
<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-4">
            <h3>Delete Booking</h3>
            <p>Are you sure you want to delete booking?</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-4">
            <form method="post" action="{% url 'deletebooking' booking.id %}">
                {% csrf_token %}
                <a href="{% url 'viewbooking' %}" class="btn btn-danger col-md-2">No</a>
                <input class="btn btn-danger col-md-2" type="submit" name="yes"/>
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}

booking/templates/view_booking.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}


<div class="delete-container">
<div class="table-responsive-sm">
    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Name</th>
                <th scope="col">Phone number</th>
                <th scope="col">Party size</th>
                <th scope="col">Time</th>
                <th scope="col">Date</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>


            </tr>
        </thead>
        <tbody>
            {% for booking in bookings %}
            <tr>
                <th scope="row"></th>
                <td>{{ booking.name }}</td>
                <td>{{ booking.phone_number }}</td>
                <td>{{ booking.party_size}}</td>
                <td>{{ booking.get_booking_time_display }}</td>
                <td>{{ booking.booking_date }}</td>
                <td>
                    <div class="intro-button mx-auto">
                        <a class="btn btn-success btn-xl" href="{% url 'editbooking' booking.id %}">Edit</a>
                    </div>
                </td>
                <td>
                    <div class="intro-button mx-auto"><a class="btn btn-primary btn-danger btn-xl"
                            href="{% url 'deletebooking' booking.id %}">Delete</a></div>
                </td>
            
            </tr>
        </tbody>
        {% endfor %}
        {% csrf_token %}
    </table>
</div>
</div>
{% endblock content %}

home/templates/index.html
{% extends "base.html" %}
{% load static %}



{% block content %}
<div class="cover" style="height:650px;">
<div class="bg-image col-md-12 align-items-center justify-content-center" style="background-image: url('{% static 'images/hero.jpeg' %}')">
    <div class="hero-text d-flex-center">
        <h3>Iconic Danish Treats</h3>
        <a href="{% url 'addbooking' %}" class="btn btn-danger col-md-12" type="button">Book Your Table</a>
    </div>
</div>
</div>
{%endblock%}

menu/templates/menu.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="container-menu"></div>
<div id="CarouselExampleCaptions" class="carousel slide" data-ride="carousel" style=" background-image: url('{% static 'images/table1.jpeg' %}')">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="item1 active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1" class="item2"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2" class="item3"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="3" class="item4"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="4" class="item5"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="5" class="item6"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="6" class="item7"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="7" class="item8"></li>
    </ol>
    <div class="carousel-inner">
        {% for item in menu %}
        <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
            <img class="img-fluid d-block w-90 mr-auto ml-auto" style="height:650px;" src="{{ item.image.url }}">
        </div>
        {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#CarouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#CarouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    {% endblock %}

templates/404_error.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="cover" style="height:650px;">
<div class="bg-image col-md-12 align-items-center justify-content-center" style="background-image: url('{% static 'images/5.jpeg' %}')">
    <div class="hero-text d-flex-center">
        <h3>Oops, this page does not exist!</h3>
        <a class="btn btn-danger btn-sm" href="{% url 'home' %}" type="button">Back to Home Page</a>
    </div>
</div>
</div>
{%endblock%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Smorrebrod</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.1/css/hover-min.css"
        type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />

</head>


<body class="d-flex flex-column min-vh-100">

    
  

    <!-- Header -->
    {% include 'includes/nav.html' %}

    {% if messages %}
    <div class="alert alert-dark">
        {% for message in messages %}
       <p {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </p>
       {% endfor %} 
       {% endif %}
    </div>

    <section>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </section>

     <!-- Footer -->
     {% include 'includes/footer.html' %}
     
<script>
    // Get all info messages
    var info_messages = document.getElementsByClassName('alert-dark');
    
    setTimeout(function(){
        for (var i = 0; i < info_messages.length; i ++) {
            // Set display attribute as !important, neccessary when using bootstrap
            info_messages[i].setAttribute('style', 'display:none !important');
        }
    }, 3000);
</script>
</body>
</html>

templates/includes/footer.html
<footer class="container-fluid mt-1 ">
    <div id="footer-details" class="row justify-content-center ">
        <div class="">
            <ul class="list-unstyled">
                <li class=" list-inline-item ">
                    <span>
                        <i class="fa fa-map-marker" aria-hidden="true"></i> 10 James Street
                    </span>
                </li>
                <li class=" list-inline-item">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    <a class="color" href=“”>
                        <span class=""> 00897653425</span>
                    </a>
                </li>
                <li class="list-inline-item">
                    <i class="fa fa-at" aria-hidden="true"></i>
                    <a class="color" href=“”>
                        <span> smorebrod@smorrebrod.com</span>
                    </a>
                </li>
                <li class="list-inline-item pr-1">
                    <a class="links-color-icon" target="_blank" href="#">
                        <i class="fa fa-pinterest" aria-hidden="true"></i>
                        <span class="sr-only">Pinterest</span>
                    </a>
                </li>
                <li class="list-inline-item pr-1">
                    <a class="links-color-icon" target="_blank" href="#">
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                        <span class="sr-only">Instagram</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="iframe-rwd" style="width: 100%">
            <iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=10%20James%20Street,%20Cork,%20Ireland+(Smorrebrod%20Gastro%20Bar)&amp;t=k&amp;z=15&amp;ie=UTF8&amp;iwloc=B&amp;output=embed">
                <a href="https://www.maps.ie/distance-area-calculator.html">measure distance on map</a>
            </iframe>
        </div>
    </div>
</footer>

templates/includes/nav.html
{% load static %}

<header>
    <div id="topheader">
    <nav class="navbar navbar-expand-lg navbar-dark bg-body-tertiary">
        <a class="navbar-brand font-weight-bold" href="{% url 'home' %}">
            <h2 class="c-white">Smorrebrod</h2>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'menu' %}">Menu</a>
                </li>
                
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" data-toggle="dropdown" aria-expanded="false">
                        Bookings
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" aria-current="page" href="{% url 'viewbooking'%}">Manage Bookings</a></li>
                        <li><a class="dropdown-item" aria-current="page" href="{% url 'addbooking' %}">New Booking</a></li>                       
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">Booking</a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
</header>